development:
  adapter: postgresql
  database: multistore_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: multistore_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: multistore_production
  pool: 5
  timeout: 5000